### ISSUE TITLE
...value of argument "maxLength" is out of range

### ISSUE THREAD

**Issue by fireflycons** [fireflycons/PSCloudFormation#122]
```
Error creating dynamic parameters: Cannot process argument because the value of argument "maxLength" is out of range. Change argument "maxLength" to  a value that is within range.
Parameter name: maxLength
Actual value was 0.
   at System.Management.Automation.ValidateLengthAttribute..ctor(Int32 minLength, Int32 maxLength)
   at Firefly.PSCloudFormation.TemplateManager.GetStackDynamicParameters(IDictionary`2 fileParameters)
```

**Comment by fireflycons** [comment]
Bug in previous change to Firefly.CloudFormation. See https://github.com/fireflycons/Firefly.CloudFormation/issues/17
